- packages/sdk/package.json
Remove cjs support
This removes CommonjJS support, we don't need `main` and `module`.
> fix(sdk): remove cjs support

- turbo.json
Fixes docs deployment failing intermittently because the output isn't cached
> chore(ops): fix turbo output

- apps/docs/docs/api/_category_.json
- apps/docs/docs/api/browser-wallets.mdx
- apps/docs/docs/getting-started/_category_.json
- apps/docs/docs/getting-started/installation.mdx
- apps/docs/docs/intro.md
- apps/docs/docusaurus.config.js
- turbo.json
Add intro, installation and browser wallet documentation
> docs(unisat): add intro, installation and browser wallet documentation

- .eslintrc.cjs
- .github/renovate.json
- .npmrc
- apps/browser-tests/package.json
- package.json
- packages/sdk/package.json
- pnpm-lock.yaml
Removed dependencies on Sticky JS and WavesHQ/Standard. Moved to Ordzaar Standard.
Fixes #
> chore(ops): move to @ordzaar/standard

- apps/browser-tests/.eslintrc.cjs
Set console to warn for browser tests
Fixes #
> fix(eslint): console

- apps/docs/src/css/custom.css
- Update the styling on `ordit-sdk` docs to match Ordzaar styling
Fixes #
> feat(docs): docs styling to match Ordzaar styling

- packages/sdk/src/fee/__fixtures__/psbt.fixture.ts
- packages/sdk/src/fee/__tests__/utils.ts
- Add mock psbt for testing
- Unblocks xverse wallet tests
> chore(psbt): add mock psbt

- packages/sdk/package.json
- packages/sdk/src/ordinals/Sattributes.ts
> fix(sdk): package json does not expose main

- apps/browser-tests/package.json
- apps/docs/package.json
- packages/sdk/package.json
- packages/sdk/vite.config.ts
- pnpm-lock.yaml
> chore(ops): add cjs as option

- apps/docs/docs/api/browser-wallets.mdx
Add missing docs for `readOnly`
Fixes #
> docs(browser-wallets): fix missing param

- packages/sdk/src/addresses/__tests__/index.spec.ts
- packages/sdk/src/addresses/index.ts
- packages/sdk/src/addresses/types.ts
- packages/sdk/src/constants/index.ts
- packages/sdk/src/transactions/helper.ts
- Add `getAddressesFromPublicKey` (used in ord-connect)
- Add tests for `getAddressesFromPublicKey`
Fixes #
> feat(sdk): add getAddressesFromPublicKey

- packages/sdk/src/addresses/index.ts
Missed this last export
Fixes #
> fix(sdk): missing constants export

- packages/sdk/src/constants/index.ts
- Attempted fix for bip32/Buffer during initialization
Fixes #
> fix(sdk): bip32 and buffer

- packages/sdk/src/transactions/__fixtures__/PSBTBuilder.fixture.ts
- packages/sdk/src/transactions/__tests__/PSBTBuilder.spec.ts
Add tests
- There is an edge case where a newly added UTXO which is being used to cover the fee is equal to the fee that is being covered. However upon adding that UTXO, the size of the new input changes and requires more fees - this is not resolved yet and is skipped since we don't know the real cost of adding that UTXO.
Fixes #
> feat(psbt): add edge case tests

- apps/browser-tests/package.json
- apps/browser-tests/tsconfig.json
- apps/docs/package.json
- apps/docs/tsconfig.json
- package.json
- packages/sdk/package.json
- packages/sdk/tsconfig.json
- pnpm-lock.yaml
> bump(deps): update deps

- apps/browser-tests/src/App.tsx
- packages/sdk/okx.d.ts
- packages/sdk/package.json
- packages/sdk/src/browser-wallets/okx/__tests__/index.spec.ts
- packages/sdk/src/browser-wallets/okx/index.ts
- packages/sdk/src/browser-wallets/okx/types.ts
- packages/sdk/src/types.d.ts
- packages/sdk/vite.config.ts
- Adds support for OKX wallet
Fixes #ORD-87
> feat(sdk): add support for OKX wallet

- packages/sdk/src/addresses/__tests__/index.spec.ts
- packages/sdk/src/addresses/index.ts
- packages/sdk/src/api/jsonrpc.ts
- packages/sdk/src/browser-wallets/internal/sats-connect/constants.ts
- packages/sdk/src/browser-wallets/internal/sats-connect/index.ts
- packages/sdk/src/browser-wallets/leather/__tests__/index.spec.ts
- packages/sdk/src/browser-wallets/leather/index.ts
- packages/sdk/src/browser-wallets/okx/__tests__/index.spec.ts
- packages/sdk/src/browser-wallets/okx/index.ts
- packages/sdk/src/browser-wallets/unisat/__tests__/index.spec.ts
- packages/sdk/src/browser-wallets/unisat/constants.ts
- packages/sdk/src/browser-wallets/unisat/index.ts
- packages/sdk/src/browser-wallets/xverse/__tests__/index.spec.ts
- packages/sdk/src/config/index.ts
- packages/sdk/src/config/types.ts
- packages/sdk/src/transactions/__tests__/PSBTBuilder.spec.ts
- packages/sdk/src/types.d.ts
- packages/sdk/src/utils/index.ts
> feat(sdk): support signet

- packages/sdk/src/browser-wallets/okx/__tests__/index.spec.ts
- packages/sdk/src/browser-wallets/okx/index.ts
- Fix: Checking of OKX wallet provider. Testnet is not supported on mobile, it should fail gracefully and not continue.
Fixes #
> fix(okx): wallet provider check

- apps/browser-tests/src/App.tsx
- apps/docs/docs/api/browser-wallets.mdx
- packages/sdk/src/addresses/index.ts
- packages/sdk/src/browser-wallets/unisat/__tests__/index.spec.ts
- packages/sdk/src/browser-wallets/unisat/constants.ts
- packages/sdk/src/browser-wallets/unisat/index.ts
- packages/sdk/src/browser-wallets/unisat/types.ts
- packages/sdk/src/config/types.ts
- packages/sdk/src/types.d.ts
- Add: Initial support for fractal bitcoin in Unisat (Transactions are currently unsupported)
- Change: Update documentation to add supported wallets
Fixes #
> feat(unisat): add initial support for fractal bitcoin

- apps/browser-tests/src/App.tsx
- packages/sdk/src/addresses/types.ts
- Fix: Chain type export
Fixes #
> feat(chain): export chain

- packages/sdk/src/browser-wallets/magiceden/index.ts
- packages/sdk/src/browser-wallets/xverse/index.ts
> fix(error): messages

- apps/browser-tests/src/App.tsx
- packages/sdk/src/addresses/index.ts
- packages/sdk/src/api/jsonrpc.ts
- packages/sdk/src/config/index.ts
- packages/sdk/src/fee/FeeEstimator.ts
- packages/sdk/src/fee/types.ts
- packages/sdk/src/modules/BaseDatasource.ts
- packages/sdk/src/modules/JsonRpcDatasource.ts
- packages/sdk/src/transactions/PSBTBuilder.ts
- packages/sdk/src/transactions/__tests__/PSBTBuilder.spec.ts
- Add: Fractal urls
- Add: chain parameter
Fixes #
Tests are required
> feat(fractal): urls and chain

- apps/browser-tests/.eslintrc.cjs
- apps/browser-tests/package.json
- apps/docs/package.json
- package.json
- packages/sdk/package.json
- pnpm-lock.yaml
> chore(deps): bump dependencies

- apps/docs/docs/api/browser-wallets.mdx
- apps/docs/docs/api/transactions.mdx
- packages/sdk/src/browser-wallets/internal/sats-connect/constants.ts
- packages/sdk/src/browser-wallets/internal/sats-connect/index.ts
- packages/sdk/src/browser-wallets/internal/sats-connect/types.ts
- packages/sdk/src/browser-wallets/unisat/constants.ts
- packages/sdk/src/types.d.ts
> feature(signet): add signet support

- packages/sdk/src/browser-wallets/internal/sats-connect/index.ts
- packages/sdk/src/browser-wallets/unisat/__tests__/index.spec.ts
- packages/sdk/src/browser-wallets/unisat/index.ts
- packages/sdk/src/browser-wallets/xverse/__tests__/index.spec.ts
> feature(signet): add signet for unisat and sats-connect

- apps/browser-tests/src/App.tsx
- packages/sdk/oyl.d.ts
- packages/sdk/package.json
- packages/sdk/phantom.d.ts
- packages/sdk/src/browser-wallets/oyl/__tests__/index.spec.ts
- packages/sdk/src/browser-wallets/oyl/index.ts
- packages/sdk/src/browser-wallets/oyl/types.ts
- packages/sdk/src/browser-wallets/phantom/__tests__/index.spec.ts
- packages/sdk/src/browser-wallets/phantom/index.ts
- packages/sdk/src/browser-wallets/phantom/types.ts
- packages/sdk/src/types.d.ts
- packages/sdk/vite.config.ts
- As titled
- Ref for phantom wallet: https://docs.phantom.com/bitcoin/detecting-the-provider
- Ref for oyl wallet: https://docs.oyl.io/help/oyl-connect/provider-api#getaddresses
Fixes #
> feat(browser-wallet): add support for phantom and oyl wallet
